FROM python:3-alpine
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY publisher.py .
CMD ["uvicorn", "publisher:app", "--host", "0.0.0.0", "--port", "8000"]
